language: node_js
node_js:
  - "8"
  - "7"
  - "6"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn
  - cd example && yarn && cd ..

before_script:
  - greenkeeper-lockfile-update
  - cd example && yarn docs && cd ..

script:
  - yarn lint
  - yarn test

after_script: greenkeeper-lockfile-upload

after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
